### ISSUE TITLE
Performance issue in browse page

### ISSUE THREAD

**Issue by fsy2001** [DanXi-Dev/DanXi-swift#146]
When scroll in browse page, there are apparent glitches in scrolling animation. This is probably caused by dynamically computing the existence of NSFW tag and hole filtering. This work should be moved to background thread to avoid UI glitches.

**Comment by singularity-s0** [comment]
<img width="799" alt="image" src="https://github.com/DanXi-Dev/DanXi-swift/assets/12184989/a2a0d01a-c5b5-472b-8205-8badc75542d5">
Profiler indicates `HoleView`s are expensive to build. All yellow frames above are `HoleView`.
