### ISSUE TITLE
[BUG] iOS 2.0.1版本无法登录UIS账号

### ISSUE THREAD

**Issue by fsoreverjun** [DanXi-Dev/DanXi-swift#155]
输入UIS账号密码后点【登录】，显示【错误 - Login failed, check username and password】。
已确认账号密码无误、不存在UIS系统验证码问题。
“旦夕账户”可正常登录。

 - 系统版本：iPadOS 17.5.1
 - 旦夕版本：2.0.1 (467)

**Comment by singularity-s0** [comment]
原密码有无特别之处？

**Comment by fsoreverjun** [comment]
> 原密码有无特别之处？

是符合UIS系统要求的正常字符（字母/数字/!@$%&*_等 常用特殊字符）

**Comment by singularity-s0** [comment]
已定位问题原因，计划于下版本修复。
