### ISSUE TITLE
无法上传图片（显示上传失败），选择图片时也无法取消（会直接退出）

### ISSUE THREAD

**Issue by JANETXSM** [DanXi-Dev/DanXi-swift#174]

**Comment by ivanfei-1** [comment]
目前图床仍旧需要校园网访问，同时编辑器还有bug

**Comment by JANETXSM** [comment]
> 目前图床仍旧需要校园网访问，同时编辑器还有bug

未连接校园网时会直接显示上传失败（不会在编辑界面出现 markdown 语法的图片链接）；连接校园网后选择图片后需要手动换行图片链接才生效

**Comment by ivanfei-1** [comment]
> > 目前图床仍旧需要校园网访问，同时编辑器还有bug
> 
> 未连接校园网时会直接显示上传失败（不会在编辑界面出现 markdown 语法的图片链接）；连接校园网后选择图片后需要手动换行图片链接才生效

这个是markdown编辑器特性，之后可以看看

**Comment by JANETXSM** [comment]
> > > 目前图床仍旧需要校园网访问，同时编辑器还有bug
> > 
> > 
> > 未连接校园网时会直接显示上传失败（不会在编辑界面出现 markdown 语法的图片链接）；连接校园网后选择图片后需要手动换行图片链接才生效
> 
> 这个是markdown编辑器特性，之后可以看看

又是这个笨markdown(^^)
