### ISSUE TITLE
无法编辑回复（显示没有管理员权限）（因为有管理权限无法复现）

### ISSUE THREAD

**Issue by JANETXSM** [DanXi-Dev/DanXi-swift#175]
![img_v3_02cc_b82b598d-6078-4971-b7e1-f5521adaae5g](https://github.com/DanXi-Dev/DanXi-swift/assets/140770462/4e61d8a4-1cd6-4b28-9220-ef6f6b2f627a)

**Comment by JANETXSM** [comment]
![img_v3_02cc_b82b598d-6078-4971-b7e1-f5521adaae5g](https://github.com/DanXi-Dev/DanXi-swift/assets/140770462/9b86fb6a-da47-4b38-93d3-bc7056f3ecc2)

**Comment by JingYiJun** [comment]
修改接口的 fold 或者 fold_v2 应该设置为 null 或者 body 里面不传递，因为设置为 空值 含义是清空 fold，需要管理员权限
