### ISSUE TITLE
Bus widgets load failed

### ISSUE THREAD

**Issue by ivanfei-1** [DanXi-Dev/DanXi-swift#196]
The `BusStore.shared.getDiskCachedRoutes()` and `Disk.retrieve("fdutools/bus.json", from: .appGroup, as: BusRoutes.self)` always return `nil`s.

**Comment by singularity-s0** [comment]
Can't reproduce on macOS or iOS.

**Comment by ivanfei-1** [comment]
getDiskCachedRoutes() does not get routes from api. getCachedRoutes(), getDiskCachedRoutes(), getRefreshedRoutes() should be merged.
