### ISSUE TITLE
BusStore API needs redesign

### ISSUE THREAD

**Issue by ivanfei-1** [DanXi-Dev/DanXi-swift#215]
getDiskCachedRoutes() does not get routes from api. getCachedRoutes(), getDiskCachedRoutes(), getRefreshedRoutes() should be merged. Related to #196.

**Comment by singularity-s0** [comment]
I didn't understand this. Please elaborate.

**Comment by singularity-s0** [comment]
The point of `getDiskCachedRoutes()` is to provide an API for widgets that loads only cached data and do not connect to the internet. It should by design not get data from API.
