### ISSUE TITLE
[BUG] 校车时刻表有误

### ISSUE THREAD

**Issue by NotoOotori** [DanXi-Dev/DanXi-swift#272]
**描述 Bug**
简要描述 Bug 是什么。
如果你认为标题已经说得很清楚了，可以删除这一项。

我相当喜欢可以在 iPadOS 上可以通过 Widget 来查看校车信息，只不过在使用过程中发现 DanXi 中的校车时刻表与实际的有出入。因为我只坐邯郸校区与江湾校区之间的校车，所以在下面我仅罗列 DanXi 相比[总务处](https://zongwuchu.fudan.edu.cn/14/bf/c39309a464063/page.htm)邯郸校区与江湾校区之间校车时刻的出入。

*** 江湾→邯郸 工作日
- 10:20 应改为 10:30，
- 11:30 应改为 11:40，
- 17:15 应改为 17:10，
- 17:35 应改为 17:30，
- 22:15 应改为 22:10。

**复现步骤**
复现该 Bug 的步骤：
1. 到 Campus 页面，
2. 点击 Bus Schedule。

**截图**
如果方便的话，你可以添加截图。

**系统信息**
 - 设备型号：iPad Pro (12.9-inch) (5th generation)
 - 系统版本：17.6.1
 - 旦挞校园助手版本（见「设置-关于本应用」）：2.0.10 (577)

**Comment by kooWZ** [comment]
这是由于双向校车在两个校区的发车时间不同，Flutter版之前也遇到过此问题
See https://github.com/DanXi-Dev/DanXi/commit/140b2dfc7231f32a4c78c27b407c8f96f51d8fe4

**Comment by NotoOotori** [comment]
感谢！
