### ISSUE TITLE
WebVPN is not working

### ISSUE THREAD

**Issue by KYLN24** [DanXi-Dev/DanXi-swift#287]
WebVPN is not working on my phone.

OS: iOS 18
Device: iPhone 15 Pro
Version: 2.1.0(592)

![0879b8cacd4689d862ee817c4e75829](https://github.com/user-attachments/assets/b7379a36-b035-4db4-91e6-803a7b022516)

**Comment by singularity-s0** [comment]
This could probably be fixed in the current main branch. Feel free to reopen if it occurs again.
