### ISSUE TITLE
“跳转回楼层”提示无法消失

### ISSUE THREAD

**Issue by fsy2001** [DanXi-Dev/DanXi-swift#363]

**Comment by singularity-s0** [comment]
Can’t reproduce.

**Comment by singularity-s0** [comment]
> https://github.com/user-attachments/assets/cc6fd1c4-cc75-4630-979c-7478f07a2fb3

Please upload the full screen recording, starting from where the popup first shows.

**Comment by singularity-s0** [comment]
Can't reproduce.

**Comment by singularity-s0** [comment]
为什么让我修一个无法复现，我也没遇到过的问题？

**Comment by singularity-s0** [comment]
除非有完整的复现方法，否则无法处理该 issue。
