### ISSUE TITLE
[Feature Request] Add a button for user to clear image cache

### ISSUE THREAD

**Issue by fsy2001** [DanXi-Dev/DanXi-swift#71]
Currently, all images downloaded from internet are cached to `cachedimages/` under caches directory. User should be able to manually clear this cache.

**Comment by singularity-s0** [comment]
Is there a good place in the UI for this button? If not,
I suggest not adding this button and set the cache to expire every 7 days.

**Comment by singularity-s0** [comment]
If we set a good auto-eviction policy, e.g. evict after 7 days or after cache exceeds 10MB, there might not be need for this button at all. We should lower UI complexity whenever we can.

**Comment by singularity-s0** [comment]
An auto-eviction policy (7 day) has been implemented. I suggest we close this issue unless there is good reason for implementing a manual eviction button.
