### ISSUE TITLE
[Bug] Multiple Button Activation by Single Tap in Reserve Page

### ISSUE THREAD

**Issue by fsy2001** [DanXi-Dev/DanXi-swift#86]
Tapping reserve button in reserve page will cause multiple buttons to be activated, as the video shows. 

https://github.com/DanXi-Dev/DanXi-swift/assets/55231108/d1670786-ee40-4731-a74a-6ac05a0899bb

This is caused by placing multiple buttons in a single list row. 
There are mainly 2 solutions:

1. Add `buttonStyle(.borderless)`
2. Remove `Grid` layout and place each row in a list row. 

I would recommend the latter.

**Comment by singularity-s0** [comment]
This is the way. https://developer.apple.com/documentation/swiftui/aligning-views-across-stacks
