### ISSUE TITLE
[Bug] Highlighting Floor Causes the View to be Invalidated

### ISSUE THREAD

**Issue by fsy2001** [DanXi-Dev/DanXi-swift#87]
https://github.com/DanXi-Dev/DanXi-swift/assets/55231108/39ba0769-fbf8-4265-9650-491ae0f3bc48

See the video. Tapping mention in 10th floor will cause 9th floor to be invalidated and redrawn. Clues: 

1. The floor flickered.
2. The time in the lower right corner updated. 

This is not the expected behavior.  What's more, the floor was also not highlighted in the video.

**Comment by singularity-s0** [comment]
SwiftUI `_printChanges()` generate the following output when highlighted: `THComplexFloor: _model changed.`

It seems that each tiny change in the model causes the entire view to update.

> What's more, the floor was also not highlighted in the video.
 
This is merely because the highlight control at `THFloorView.swift:72` has been commented out.
